### ISSUE TITLE
Incorrect calls to getrusage()

### ISSUE THREAD

**Issue by PeterCoghlan** [Fish-Git/hyperion#10] opened 2017-04-12 10:40 UTC
Please take a look at issue #217 on the hercules-390/hyperion issues page as the same code is present in this fork.

While it looks likely that the issue arises only on Linux or other unix platforms and probably does not arise on Windows platforms, I suspect there is a desire here to ensure things work correctly on all platforms and that use is not made of undocumented features.

**Comment by Fish-Git** [comment] 2017-04-13 19:40
Hi Peter!

Yes, I saw that.  I monitor hercules-390/hyperion's issues so I bookmarked the relevant posts so I could address the issue in my Hyperion as well.

There have been several other changes made to hercules-390/hyperion over the past month or so too, which I have not yet gotten around to applying to my Hyperion yet due to not only personal life issues(*) but also due to my not having finished yet with the changes I'm currently working on. It's one of those changes that started out simple but then snowballed into a much larger and more complicated change due to discovered bugs leading to yet other bugs, etc. Attention to detail is important to me and the closer I look at things the more problems I'm seeing. As a result, my "simple" change is taking much longer than expected. (You know what they say: "The last 1% of a project takes 99% of the time and effort.")

Anyway... once I finish what I'm working on I will return to addressing one by one all of the most recently raised issues, yours (getrusage) being one of them.

In the mean time I appreciate your having taken the time to report this to me (my hyperion) and ask for your continued patience as I work through my personal and Hercules issues as quickly as I can.

Thanks.

----------------------------------------
(*) My wife became very ill and was taken to the hospital last week. She spent 6 days there slowly getting better and was discharged just this past Sunday. She is now spending another week convalescing at home and hopes to return back to work on Monday. Her physical and emotional well being of course takes precedence over anything/everything else in my life. She is my world. My own needs are a distant second, and Hercules? ... well, the difference between their respective importance is lightyears apart.

**Comment by Fish-Git** [comment] 2018-01-20 14:27
This issue is a duplicate of issue #79 "Incorrect CPU Timer - Now Corrected".

**Comment by Fish-Git** [comment] 2018-01-20 14:31
This issue is resolved by (or rather, _will be_ resolved by) pull request #79 "Incorrect CPU Timer - Now Corrected", which have already merged into my test respository.

Once I am finished withwhat I'm currently working on, the fix (pull request #79 "Incorrect CPU Timer - Now Corrected") will appear in this publicly visible fish-git/hyperion repository.

**Comment by Fish-Git** [comment] 2018-02-26 23:46
**UPDATE:** This issue is _now_ a duplicate of issue **_#83_** "_CPU Timer Fix Stopping 2nd Level VM ABENDs_" (_not_ issue #79).

I am closing this issue.

The originally reported problem will be eventually fixed by issue #83.

**Closed by Fish-Git** 2018-02-26 23:46 UTC
Labels: BUG, Duplicate, IN PROGRESS...
